# mysql-restore-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: mysql-restore
spec:
  template:
    spec:
      containers:
        - name: mysql-restore
          image: mysql:8.0
          command:
            - /bin/bash
            - -c
            - |
              mysql -h mysql -u root -p$MYSQL_ROOT_PASSWORD $MYSQL_DATABASE < /backup/dbDump/backup1021.sql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "1234"
            - name: MYSQL_DATABASE
              value: "parandb"
          volumeMounts:
            - name: backup-volume
              mountPath: /backup
      volumes:
        - name: backup-volume
          hostPath:
            path: /backup/dbDump  # 백업 파일이 있는 호스트 경로
      restartPolicy: Never

---
# mongodb-restore-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: mongodb-restore
spec:
  template:
    spec:
      containers:
        - name: mongodb-restore
          image: mongo:latest
          command:
            - /bin/bash
            - -c
            - |
              mongorestore --host mongodb --username root --password 1234  --authenticationDatabase admin /backup/dbDump/backupMongo
          volumeMounts:
            - name: backup-volume
              mountPath: /backup
      volumes:
        - name: backup-volume
          hostPath:
            path: /backup/dbDump
      restartPolicy: Never